// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hobdcfyberenfcayxgoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYmRjZnliZXJlbmZjYXl4Z29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTU0OTcsImV4cCI6MjA2Nzc5MTQ5N30.5FDfabRhu_tpsNHNE7kUjS6OQojlcMasCpfac4Z3yWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});